import "./global.css";
import Link from "next/link";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-slate-200 shadow-md">
          <div className="flex justify-between items-center max-w-6xl mx-auto p-3">
            <Link href="/">
              <h1 className="font-bold text-sm sm:text-xl flex flex-wrap">
                <span className="text-slate-500">jst</span>
                <span className="text-slate-700">Clk</span>
              </h1>
            </Link>
            <ul className="flex gap-5">
              <li className="text-xs md-text-base text-slate-700 hover:underline">
                <Link href="/about">About </Link>
              </li>

              <li className="text-xs md-text-base text-slate-700 hover:underline">
                <Link href="/gallery">Gallery </Link>
              </li>

              <li className="text-xs md-text-base text-slate-700 hover:underline">
                <Link href="/contact">Contact </Link>
              </li>
            </ul>
          </div>
        </header>


        <main className="container mx-auto p-10">
          {children}
          </main>


      </body>
    </html>
  );
}
